[project]
name = "mcp-code-exec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.4",
]

[dependency-groups]
test = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "sympy>=1.14.0",
]
